/* LISTADO DE LAS VIVIENDAS CON SU RESPECTIVO ESTADO Y SI ESTÁN DISPONIBLES */
SELECT VIVIENDA.CODVIV AS VIVIENDA, VIVIENDA_ESTADO.DESESTVIV AS ESTADO
FROM VIVIENDA
INNER JOIN VIVIENDA_ESTADO
ON VIVIENDA_ESTADO.CODVIVEST = VIVIENDA.CODVIVEST
;
--- Agregar un campo de Disponibilidad (D<Disponible> N<No Disponible>) ---

/* LISTADO DE LOS INQUILINOS QUE TIENEN MÁS CASAS ALQUILADAS */
SELECT ALQUILER_DETALLE.CODALQDET,Concat(PERSONA.NOMPER,concat(' ',concat(PERSONA.APEPATPER,concat(' ',PERSONA.APEMATPER)))) as PERSONA
FROM ALQUILER_DETALLE
INNER JOIN ALQUILER
ON ALQUILER.CODALQ = ALQUILER_DETALLE.CODALQ
INNER JOIN PERSONA
ON PERSONA.CODPER = ALQUILER.CODPERINQ
;

/* RESULTADO DE LA GANANCIA DE LOS DEPARTAMENTOS RENTADOS POR MES O AÑO */


/* LISTADO DE LOS DEPARTAMENTOS QUCOUNT([ALL | DISTINCT] expr)E SE VENCE LA MENSUALIDAD */


/* LISTA INQUILINOS QUE FALTAN PAGAR */


/* CUÁLES SON LOS DEPARTAMENTOS QUE SE RENTAN CON MÁS FRECUENCIA Y CUÁLES NO */


