/* CONSULTA DE LA TABLA DETALLE DEPARTAMENTO, CONOCIENDO EL CARGO QUE TIENE LA PERSONA Y EN QUE DEPARTAMENTO ESTA ASIGNADO Y SU UBICACION (SOLO SUPERVID) */
CREATE VIEW VW_CONSULTA
AS
SELECT TO_CHAR(FECINIDETDEP ,'DD/MM/YYYY') AS "FECHA DE INICIO", NOMCAR AS CARGO,(NOMPER||' '||APEPATEPER||' '||APEMATEPER) AS PERSONA,
NOMDEP AS DEPARTAMENTO, SALADETDEP AS SALARIO, SEGPER AS "SEGURO SOCIAL",
(UPPER(UBIGEO.DISTUBI||', '||UBIGEO.DEPTUBI||', '||UBIGEO.PROVUBI)) AS "UBICACION DEL DEPARTAMENTO"
FROM DETALLE_DEPARTAMENTO
INNER JOIN PERSONA ON DETALLE_DEPARTAMENTO.PERSONA_CODPER = PERSONA.CODPER
INNER JOIN DEPARTAMENTO ON DETALLE_DEPARTAMENTO.DEPARTAMENTO_CODDEP = DEPARTAMENTO.CODDEP
INNER JOIN UBIGEO ON DEPARTAMENTO.UBIGEO_CODUBI = UBIGEO.CODUBI
INNER JOIN UBIGEO ON PERSONA.UBIGEO_CODUBI = UBIGEO.CODUBI
WHERE NOMCAR LIKE 'SUPERVISOR' 
ORDER BY FECINIDETDEP ASC;

/* CONSULTA DE LA TABLA DETALLE FAMILIA, CON LA PERSONA Y SU FAMILIAR */
SELECT PARENDETFAM, (UPPER(PERSONA.NOMPER||' '||PERSONA.APEPATEPER||' '||PERSONA.APEMATEPER)) AS PERSONA,
(UPPER(PERSONA.NOMPER||' '||PERSONA.APEPATEPER||' '||PERSONA.APEMATEPER)) AS FAMILIAR,TIPPER
FROM DETALLE_FAMILIA
INNER JOIN PERSONA ON DETALLE_FAMILIA.PERSONA_CODPER = PERSONA.CODPER
WHERE TIPPER LIKE 'F';

/* CONSULTA DE LA TABLA DETALLE_PROYECTO, CON LA PERSONA ENCARGADA, MAS EL POYECTO Y LA CANTIDAD DE HORAS TRABAJADAS POR DIA  */
SELECT (UPPER(PROYECTO.NOMPRO)) AS PROYECTO, DESCRES AS "DESCRIPCION DEL PROYECTO", 
(UPPER(PERSONA.NOMPER||' '||PERSONA.APEPATEPER||' '||PERSONA.APEMATEPER)) AS PERSONAL, HORDETPRO AS HORAS
FROM DETALLE_PROYECTO 
INNER JOIN PERSONA ON DETALLE_PROYECTO.PERSONA_CODPER = PERSONA.CODPER
INNER JOIN PROYECTO ON DETALLE_PROYECTO.PROYECTO_CODPRO = PROYECTO.CODPRO
ORDER BY HORDETPRO ASC;

/* CONSULTA DE LA TABLA PERSONA, CON SU DIRECCION, SOLO FAMILIARES */
SELECT (UPPER(NOMPER||', '||APEPATEPER||', '||APEMATEPER)) AS PERSONA, TO_CHAR(FECNACPER,'DD/MM/YYYY') AS "FECHA NACIMIENTO", 
DNIPER, SEXPER,USUPER, PASSWPER, (UPPER(UBIGEO.DISTUBI||', '||UBIGEO.PROVUBI||', '||UBIGEO.DEPTUBI)) AS DIRECCION
FROM PERSONA
INNER JOIN UBIGEO ON PERSONA.UBIGEO_CODUBI = UBIGEO.CODUBI
WHERE TIPPER LIKE 'F'
ORDER BY PERSONA ASC;

/* CONSULTA DE LA TABLA PERSONA, CON SU DIRECCION, SOLO FAMILIARES, SOLO TRABAJADORES    */
SELECT (UPPER(NOMPER||', '||APEPATEPER||', '||APEMATEPER)) AS PERSONA, TO_CHAR(FECNACPER,'DD/MM/YYYY') AS "FECHA NACIMIENTO", 
DNIPER, SEXPER,USUPER, PASSWPER, (UPPER(UBIGEO.DISTUBI||', '||UBIGEO.PROVUBI||', '||UBIGEO.DEPTUBI)) AS DIRECCION
FROM PERSONA
INNER JOIN UBIGEO ON PERSONA.UBIGEO_CODUBI = UBIGEO.CODUBI
WHERE TIPPER LIKE 'T'
ORDER BY FECNACPER ASC;

/* CONSULTA DE LA TABLA DEPARTAMENTO, CON SU UBICACION */
SELECT NOMDEP AS "NOMBRE DEL DEPARTAMENTO",(UPPER(UBIGEO.DISTUBI||', '||UBIGEO.PROVUBI||', '||UBIGEO.DEPTUBI)) AS UBICACION
FROM DEPARTAMENTO
INNER JOIN UBIGEO ON DEPARTAMENTO.UBIGEO_CODUBI = UBIGEO.CODUBI
ORDER BY NOMDEP ASC

/*  */



